replicaCount: 2

image:
  repository: jmsajib11/my-app
  tag: "a73e2643ca4fd1e3703234b8ff5c6b08e5b723a1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources: {}