replicaCount: 2

image:
  repository: jmsajib11/my-app
  tag: "b40051745d15f84f7780fe17b88ab39e7d76eca0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources: {}